# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fraud_detection import fraud_detection_pb2 as fraud__detection_dot_fraud__detection__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fraud_detection/fraud_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/InitializeOrder',
                request_serializer=fraud__detection_dot_fraud__detection__pb2.OrderInitializationRequest.SerializeToString,
                response_deserializer=fraud__detection_dot_fraud__detection__pb2.OrderInitializationResponse.FromString,
                _registered_method=True)
        self.CheckUserFraud = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/CheckUserFraud',
                request_serializer=fraud__detection_dot_fraud__detection__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=fraud__detection_dot_fraud__detection__pb2.OrderEventResponse.FromString,
                _registered_method=True)
        self.CheckCardFraud = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/CheckCardFraud',
                request_serializer=fraud__detection_dot_fraud__detection__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=fraud__detection_dot_fraud__detection__pb2.OrderEventResponse.FromString,
                _registered_method=True)
        self.ClearOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/ClearOrder',
                request_serializer=fraud__detection_dot_fraud__detection__pb2.OrderClearRequest.SerializeToString,
                response_deserializer=fraud__detection_dot_fraud__detection__pb2.OrderClearResponse.FromString,
                _registered_method=True)
        self.CheckFraud = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/CheckFraud',
                request_serializer=fraud__detection_dot_fraud__detection__pb2.OrderRequest.SerializeToString,
                response_deserializer=fraud__detection_dot_fraud__detection__pb2.FraudResponse.FromString,
                _registered_method=True)


class FraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCardFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeOrder,
                    request_deserializer=fraud__detection_dot_fraud__detection__pb2.OrderInitializationRequest.FromString,
                    response_serializer=fraud__detection_dot_fraud__detection__pb2.OrderInitializationResponse.SerializeToString,
            ),
            'CheckUserFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserFraud,
                    request_deserializer=fraud__detection_dot_fraud__detection__pb2.OrderEventRequest.FromString,
                    response_serializer=fraud__detection_dot_fraud__detection__pb2.OrderEventResponse.SerializeToString,
            ),
            'CheckCardFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCardFraud,
                    request_deserializer=fraud__detection_dot_fraud__detection__pb2.OrderEventRequest.FromString,
                    response_serializer=fraud__detection_dot_fraud__detection__pb2.OrderEventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=fraud__detection_dot_fraud__detection__pb2.OrderClearRequest.FromString,
                    response_serializer=fraud__detection_dot_fraud__detection__pb2.OrderClearResponse.SerializeToString,
            ),
            'CheckFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFraud,
                    request_deserializer=fraud__detection_dot_fraud__detection__pb2.OrderRequest.FromString,
                    response_serializer=fraud__detection_dot_fraud__detection__pb2.FraudResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_detection.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud_detection.FraudDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_detection.FraudDetectionService/InitializeOrder',
            fraud__detection_dot_fraud__detection__pb2.OrderInitializationRequest.SerializeToString,
            fraud__detection_dot_fraud__detection__pb2.OrderInitializationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_detection.FraudDetectionService/CheckUserFraud',
            fraud__detection_dot_fraud__detection__pb2.OrderEventRequest.SerializeToString,
            fraud__detection_dot_fraud__detection__pb2.OrderEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckCardFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_detection.FraudDetectionService/CheckCardFraud',
            fraud__detection_dot_fraud__detection__pb2.OrderEventRequest.SerializeToString,
            fraud__detection_dot_fraud__detection__pb2.OrderEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_detection.FraudDetectionService/ClearOrder',
            fraud__detection_dot_fraud__detection__pb2.OrderClearRequest.SerializeToString,
            fraud__detection_dot_fraud__detection__pb2.OrderClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_detection.FraudDetectionService/CheckFraud',
            fraud__detection_dot_fraud__detection__pb2.OrderRequest.SerializeToString,
            fraud__detection_dot_fraud__detection__pb2.FraudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
