# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from order_queue import order_queue_pb2 as order__queue_dot_order__queue__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in order_queue/order_queue_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderQueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Enqueue = channel.unary_unary(
                '/order_queue.OrderQueueService/Enqueue',
                request_serializer=order__queue_dot_order__queue__pb2.EnqueueRequest.SerializeToString,
                response_deserializer=order__queue_dot_order__queue__pb2.EnqueueResponse.FromString,
                _registered_method=True)
        self.Dequeue = channel.unary_unary(
                '/order_queue.OrderQueueService/Dequeue',
                request_serializer=order__queue_dot_order__queue__pb2.DequeueRequest.SerializeToString,
                response_deserializer=order__queue_dot_order__queue__pb2.DequeueResponse.FromString,
                _registered_method=True)
        self.GetQueueSize = channel.unary_unary(
                '/order_queue.OrderQueueService/GetQueueSize',
                request_serializer=order__queue_dot_order__queue__pb2.GetQueueSizeRequest.SerializeToString,
                response_deserializer=order__queue_dot_order__queue__pb2.GetQueueSizeResponse.FromString,
                _registered_method=True)
        self.PeekOrder = channel.unary_unary(
                '/order_queue.OrderQueueService/PeekOrder',
                request_serializer=order__queue_dot_order__queue__pb2.PeekOrderRequest.SerializeToString,
                response_deserializer=order__queue_dot_order__queue__pb2.PeekOrderResponse.FromString,
                _registered_method=True)
        self.RegisterExecutor = channel.unary_unary(
                '/order_queue.OrderQueueService/RegisterExecutor',
                request_serializer=order__queue_dot_order__queue__pb2.RegisterExecutorRequest.SerializeToString,
                response_deserializer=order__queue_dot_order__queue__pb2.RegisterExecutorResponse.FromString,
                _registered_method=True)
        self.GetLeader = channel.unary_unary(
                '/order_queue.OrderQueueService/GetLeader',
                request_serializer=order__queue_dot_order__queue__pb2.GetLeaderRequest.SerializeToString,
                response_deserializer=order__queue_dot_order__queue__pb2.GetLeaderResponse.FromString,
                _registered_method=True)


class OrderQueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Enqueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueSize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeekOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterExecutor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderQueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Enqueue': grpc.unary_unary_rpc_method_handler(
                    servicer.Enqueue,
                    request_deserializer=order__queue_dot_order__queue__pb2.EnqueueRequest.FromString,
                    response_serializer=order__queue_dot_order__queue__pb2.EnqueueResponse.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=order__queue_dot_order__queue__pb2.DequeueRequest.FromString,
                    response_serializer=order__queue_dot_order__queue__pb2.DequeueResponse.SerializeToString,
            ),
            'GetQueueSize': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueSize,
                    request_deserializer=order__queue_dot_order__queue__pb2.GetQueueSizeRequest.FromString,
                    response_serializer=order__queue_dot_order__queue__pb2.GetQueueSizeResponse.SerializeToString,
            ),
            'PeekOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PeekOrder,
                    request_deserializer=order__queue_dot_order__queue__pb2.PeekOrderRequest.FromString,
                    response_serializer=order__queue_dot_order__queue__pb2.PeekOrderResponse.SerializeToString,
            ),
            'RegisterExecutor': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterExecutor,
                    request_deserializer=order__queue_dot_order__queue__pb2.RegisterExecutorRequest.FromString,
                    response_serializer=order__queue_dot_order__queue__pb2.RegisterExecutorResponse.SerializeToString,
            ),
            'GetLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeader,
                    request_deserializer=order__queue_dot_order__queue__pb2.GetLeaderRequest.FromString,
                    response_serializer=order__queue_dot_order__queue__pb2.GetLeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order_queue.OrderQueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('order_queue.OrderQueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderQueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Enqueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order_queue.OrderQueueService/Enqueue',
            order__queue_dot_order__queue__pb2.EnqueueRequest.SerializeToString,
            order__queue_dot_order__queue__pb2.EnqueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order_queue.OrderQueueService/Dequeue',
            order__queue_dot_order__queue__pb2.DequeueRequest.SerializeToString,
            order__queue_dot_order__queue__pb2.DequeueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueSize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order_queue.OrderQueueService/GetQueueSize',
            order__queue_dot_order__queue__pb2.GetQueueSizeRequest.SerializeToString,
            order__queue_dot_order__queue__pb2.GetQueueSizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PeekOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order_queue.OrderQueueService/PeekOrder',
            order__queue_dot_order__queue__pb2.PeekOrderRequest.SerializeToString,
            order__queue_dot_order__queue__pb2.PeekOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterExecutor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order_queue.OrderQueueService/RegisterExecutor',
            order__queue_dot_order__queue__pb2.RegisterExecutorRequest.SerializeToString,
            order__queue_dot_order__queue__pb2.RegisterExecutorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/order_queue.OrderQueueService/GetLeader',
            order__queue_dot_order__queue__pb2.GetLeaderRequest.SerializeToString,
            order__queue_dot_order__queue__pb2.GetLeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
