# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\"@\n\x05Order\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x12\n\norder_json\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"3\n\x0e\x45nqueueRequest\x12!\n\x05order\x18\x01 \x01(\x0b\x32\x12.order_queue.Order\"J\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0equeue_position\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"=\n\x0e\x44\x65queueRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65xecutor_token\x18\x02 \x01(\t\"i\n\x0f\x44\x65queueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12!\n\x05order\x18\x02 \x01(\x0b\x32\x12.order_queue.Order\x12\x12\n\ndequeue_id\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\"\x15\n\x13GetQueueSizeRequest\"*\n\x14GetQueueSizeResponse\x12\x12\n\nqueue_size\x18\x01 \x01(\x05\"$\n\x10PeekOrderRequest\x12\x10\n\x08position\x18\x01 \x01(\x05\"F\n\x11PeekOrderResponse\x12!\n\x05order\x18\x01 \x01(\x0b\x32\x12.order_queue.Order\x12\x0e\n\x06\x65xists\x18\x02 \x01(\x08\x32\xc0\x02\n\x11OrderQueueService\x12\x44\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponse\x12S\n\x0cGetQueueSize\x12 .order_queue.GetQueueSizeRequest\x1a!.order_queue.GetQueueSizeResponse\x12J\n\tPeekOrder\x12\x1d.order_queue.PeekOrderRequest\x1a\x1e.order_queue.PeekOrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=34
  _globals['_ORDER']._serialized_end=98
  _globals['_ENQUEUEREQUEST']._serialized_start=100
  _globals['_ENQUEUEREQUEST']._serialized_end=151
  _globals['_ENQUEUERESPONSE']._serialized_start=153
  _globals['_ENQUEUERESPONSE']._serialized_end=227
  _globals['_DEQUEUEREQUEST']._serialized_start=229
  _globals['_DEQUEUEREQUEST']._serialized_end=290
  _globals['_DEQUEUERESPONSE']._serialized_start=292
  _globals['_DEQUEUERESPONSE']._serialized_end=397
  _globals['_GETQUEUESIZEREQUEST']._serialized_start=399
  _globals['_GETQUEUESIZEREQUEST']._serialized_end=420
  _globals['_GETQUEUESIZERESPONSE']._serialized_start=422
  _globals['_GETQUEUESIZERESPONSE']._serialized_end=464
  _globals['_PEEKORDERREQUEST']._serialized_start=466
  _globals['_PEEKORDERREQUEST']._serialized_end=502
  _globals['_PEEKORDERRESPONSE']._serialized_start=504
  _globals['_PEEKORDERRESPONSE']._serialized_end=574
  _globals['_ORDERQUEUESERVICE']._serialized_start=577
  _globals['_ORDERQUEUESERVICE']._serialized_end=897
# @@protoc_insertion_point(module_scope)
