# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from transaction_verification import transaction_verification_pb2 as transaction__verification_dot_transaction__verification__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in transaction_verification/transaction_verification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionVerificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/InitializeOrder',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.OrderInitializationRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderInitializationResponse.FromString,
                _registered_method=True)
        self.VerifyItemsNonEmpty = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyItemsNonEmpty',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
                _registered_method=True)
        self.VerifyUserData = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyUserData',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
                _registered_method=True)
        self.VerifyCreditCard = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyCreditCard',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
                _registered_method=True)
        self.ClearOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/ClearOrder',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.OrderClearRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderClearResponse.FromString,
                _registered_method=True)
        self.VerifyTransaction = channel.unary_unary(
                '/transaction_verification.TransactionVerificationService/VerifyTransaction',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.TransactionRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.TransactionResponse.FromString,
                _registered_method=True)


class TransactionVerificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyItemsNonEmpty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCreditCard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeOrder,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderInitializationRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.OrderInitializationResponse.SerializeToString,
            ),
            'VerifyItemsNonEmpty': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyItemsNonEmpty,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.SerializeToString,
            ),
            'VerifyUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUserData,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.SerializeToString,
            ),
            'VerifyCreditCard': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCreditCard,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderClearRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.OrderClearResponse.SerializeToString,
            ),
            'VerifyTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyTransaction,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.TransactionRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction_verification.TransactionVerificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transaction_verification.TransactionVerificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionVerificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/InitializeOrder',
            transaction__verification_dot_transaction__verification__pb2.OrderInitializationRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.OrderInitializationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyItemsNonEmpty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/VerifyItemsNonEmpty',
            transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/VerifyUserData',
            transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyCreditCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/VerifyCreditCard',
            transaction__verification_dot_transaction__verification__pb2.OrderEventRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.OrderEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/ClearOrder',
            transaction__verification_dot_transaction__verification__pb2.OrderClearRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.OrderClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerificationService/VerifyTransaction',
            transaction__verification_dot_transaction__verification__pb2.TransactionRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
